SLEEP_TIME = 0.03
PIXEL_BLOCK = 21
STEP_BLOCK = PIXEL_BLOCK / 4
SCORE_FONT = 32

SCREEN_PADDING_LEFT = 5
SCREEN_PADDING_BOTTOM = 5

SCREEN_WIDTH: int = 700
SCREEN_HEIGHT: int = 350

STRETCH_LENGTH = 0.5
STRETCH_HEIGHT = 2.5
BALL_STRETCH = 0.5
BALL_RADIUS = PIXEL_BLOCK * BALL_STRETCH
BALL_ANGLE = 45

PADDLE_WIDTH = PIXEL_BLOCK * STRETCH_LENGTH
PADDLE_HEIGHT = PIXEL_BLOCK * STRETCH_HEIGHT

LEFT_BOUND = 0 - SCREEN_PADDING_LEFT
RIGHT_BOUND = SCREEN_WIDTH + (1 - STRETCH_LENGTH) * PADDLE_WIDTH

UPPER_BOUND = SCREEN_HEIGHT
LOWER_BOUND = 0 - SCREEN_PADDING_BOTTOM

INIT_COR = {'left': {'x': LEFT_BOUND,
                     'y': (UPPER_BOUND - LOWER_BOUND) / 2},
            'right': {'x': RIGHT_BOUND - PADDLE_WIDTH,
                      'y': (UPPER_BOUND - LOWER_BOUND) / 2},
            'ball': {'x': (UPPER_BOUND - LOWER_BOUND) / 2,
                     'y': LOWER_BOUND + PIXEL_BLOCK},
            }
